language: python

matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36

install:
  - pip install tox

script:
  - black --check .
  - isort --diff --check-only --recursive
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
