name: Publish to Test PyPi

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - 'pyproject.toml'

jobs:
  publish_to_test_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v6
    - name: Build
      run: uv build
    - name: Publish to Test PyPI
      env:
        UV_PUBLISH_USERNAME: ${{ secrets.test_pypi_username }}
        UV_PUBLISH_PASSWORD: ${{ secrets.test_pypi_password }}
      run: uv publish --publish-url https://test.pypi.org/legacy/
