name: Publish to Test PyPi

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - 'pyproject.toml'

jobs:
  publish_to_test_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: |
        python -m build twine
        twine upload --skip-existing --repository testpypi dist/*
