name: Tests

on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: python -m pip install -r requirements_test.txt
      - name: Lint
        run: |
          black --check .
          flake8 .
          isort **/*.py -c

  linux_tests:
    name: Linux - Python ${{ matrix.python-version }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.12, 3.11.4]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements_test.txt
      - name: Run tests for ${{ matrix.python-version }}
        run: pytest -vvv

  windows_tests:
    name: Windows - Python ${{ matrix.python-version }}
    needs: linux_tests
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.12, 3.11.4]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements_test.txt
      - name: Run tests for ${{ matrix.python-version }}
        run: pytest -vvv
