name: Tests

on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: python -m pip install -r requirements_test.txt
      - name: Lint
        run: pre-commit run --all-files

  tests:
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10.12, 3.11.4, 3.12, 3.13-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install -r requirements.txt
          python -m pip install .
      - name: Run tests for ${{ matrix.python-version }}
        run: pytest -vvv
